# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_company', models.CharField(max_length=64)),
                ('trip_date', models.DateTimeField(verbose_name='date of trip')),
                ('departure_city', models.CharField(max_length=64)),
                ('arrival_city', models.CharField(max_length=64)),
                ('author', models.CharField(default='Anonymous', max_length=64)),
                ('review', models.CharField(max_length=500)),
                ('speed', models.IntegerField(choices=[(1, 'Pole Pole'), (2, 'Kama Kawaida'), (3, 'Faster than Usual')])),
                ('safety', models.IntegerField(default=0)),
                ('comfort', models.IntegerField(default=0)),
                ('recomendations', models.IntegerField(default=0)),
            ],
        ),
    ]
