# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 19:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=64)),
                ('loc_lat', models.FloatField()),
                ('loc_lon', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='bustrip',
            name='departure_time',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
        migrations.AlterField(
            model_name='bustrip',
            name='arrival_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arival_city', to='travel.City'),
        ),
        migrations.AlterField(
            model_name='bustrip',
            name='comfort',
            field=models.IntegerField(choices=[(1, '1 - Painful'), (2, '2 - Siyo Mbaya'), (3, '3 - Safi Sana')]),
        ),
        migrations.AlterField(
            model_name='bustrip',
            name='departure_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_city', to='travel.City'),
        ),
        migrations.AlterField(
            model_name='bustrip',
            name='review',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bustrip',
            name='safety',
            field=models.IntegerField(choices=[(1, '1 - Scary'), (2, '2 - On Par'), (3, '3 - Salama')]),
        ),
        migrations.AlterField(
            model_name='bustrip',
            name='speed',
            field=models.IntegerField(choices=[(1, '1 - Pole Pole'), (2, '2 - Kama Kawaida'), (3, '3 - Faster than Usual')]),
        ),
        migrations.AlterField(
            model_name='bustrip',
            name='trip_date',
            field=models.DateField(verbose_name='date of trip'),
        ),
    ]
