# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20160509_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bustrip',
            name='arrival_city',
        ),
        migrations.AddField(
            model_name='bustrip',
            name='arrival_city',
            field=models.ManyToManyField(related_name='arrival_city', to='travel.City'),
        ),
        migrations.RemoveField(
            model_name='bustrip',
            name='departure_city',
        ),
        migrations.AddField(
            model_name='bustrip',
            name='departure_city',
            field=models.ManyToManyField(related_name='departure_city', to='travel.City'),
        ),
    ]
